routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function() {
    Route::resource('teacher', 'TeacherController', ['except' => ['show']]);
    Route::resource('student', 'StudentController', ['except' => ['show']]);
    Route::resource('class', 'ClassController');
    Route::get('/class/pdf/download', 'ClassController@download')->name('class.download');
    Route::post('/class/pdf/download', 'ClassController@getPDF')->name('class.getPDF');
});

app/Http/Controllers/ClassController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB, Exception, PDF, Validator;
use App\Classes;
use App\Student;
use App\Teacher;

class ClassController extends Controller
{
    public function index(Request $request)
    {
        $classes = Classes::paginate(10);
        $data = [
            'classes' => $classes
        ];
        return view('class.index', $data);
    }

    public function create()
    {
        $teachers = Teacher::all();
        $data = [
            'teachers' => $teachers
        ];
        return view('class.create', $data);
    }

    public function store(Request $request)
    {
        DB::beginTransaction();
        try {
            $validator = Validator::make($request->all(), [
                'name' => 'required|max:20',
                'teacher_id' => 'required'
            ]);
            if($validator->fails()) {
                return redirect('class/create')->withErrors($validator)->withInput();
            }

            $class = new Classes();
            $class->name = $request->name;
            $class->teacher_id = $request->teacher_id;
            $class->save();
            DB::commit();

            return redirect()->route('class.index')->with('flash_data', 'Data successfully created!');
        } catch(Exception $e) {
            DB::rollback();
            return view('errors.500');
        }
    }

    public function show($id)
    {
        $class = Classes::find($id);
        if(empty($class)) {
            return view('errors.500');
        }
        $students = Student::where("class_id", "!=", $class->id)->get();
        $data = [
            'class' => $class,
            'students' => $students
        ];
        return view('class.show', $data);
    }

    public function edit($id)
    {
        $class = Classes::find($id);
        if(empty($class)) {
            return view('errors.404');
        }
        $teachers = Teacher::all();
        $data = [
            'class' => $class,
            'teachers' => $teachers
        ];
        return view('class.edit', $data);
    }

    public function update(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $validator = Validator::make($request->all(), [
                'name' => 'required|max:20',
                'teacher_id' => 'required'
            ]);
            if($validator->fails()) {
                return redirect()->route('class.edit', $id)->withErrors($validator)->withInput();
            }

            $class = Classes::find($id);
            if(empty($class)) {
                return view('errors.500');
            }
            $class->name = $request->name;
            $class->teacher_id = $request->teacher_id;
            $class->save();
            DB::commit();

            return redirect()->route('class.index')->with('flash_data', 'Data successfully updated!');
        } catch(Exception $e) {
            DB::rollback();
            return view('errors.500');
        }
    }

    public function destroy(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $class = Classes::find($id);
            if(empty($class)) {
                return view('errors.500');
            }
            $class->delete();
            DB::commit();

            return redirect()->route('class.index')->with('flash_data', 'Data successfully deleted!');
        } catch(Exception $e) {
            DB::rollback();
            return view('errors.500');
        }
    }

    public function download()
    {
        return view('class.download');
    }

    public function getPDF(Request $request)
    {
        try {
            if($request->id) {
                $classes = Classes::where('id', $request->id)->get();
            } else {
                $classes = Classes::all();
            }
            if(empty($classes)) {
                return view('errors.500');
            }
            $data = [
                'classes' => $classes
            ];
            $pdf = PDF::loadView('class.pdf_template', $data);
            return $pdf->stream();
        } catch(Exception $e) {
            return view('errors.500');
        }
    }
}

resources/views/class/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ Breadcrumbs::render('class.create') }}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Class</div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            {{ $errors->all()[0] }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('class.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="teacher_id">Teacher</label>
                            <select name="teacher_id" class="form-control">
                                @foreach($teachers as $teacher)
                                    <option value="{{ $teacher->id }}">{{ $teacher->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{{ route('class.index') }}">
                            <button type="button" class="btn btn-default">Cancel</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/class/download.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ Breadcrumbs::render('class.download') }}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Class</div>

                <div class="card-body">
                    <p>Klik button bellow to download file.</p>
                    <button type="button" class="btn btn-primary"
                        onclick="event.preventDefault();
                                    $('#download-form').submit();">
                        Download</button>
                    <form id="download-form" action="{{ route('class.getPDF') }}"
                        method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/class/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ Breadcrumbs::render('class.edit', $class) }}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Class</div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            {{ $errors->all()[0] }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('class.update', $class->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control" value="{{ $class->name }}">
                        </div>
                        <div class="form-group">
                            <label for="teacher_id">Teacher</label>
                            <select name="teacher_id" class="form-control">
                                @foreach($teachers as $teacher)
                                    <option value="{{ $teacher->id }}"
                                        @if($teacher->id == $class->teacher_id)
                                            selected
                                        @endif >
                                        {{ $teacher->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{{ route('class.index') }}">
                            <button type="button" class="btn btn-default">Cancel</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/class/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ Breadcrumbs::render('class.index') }}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Class</div>

                <div class="card-body">
                    @if (session('flash_data'))
                        <div class="alert alert-success">
                            {{ session('flash_data') }}
                        </div>
                    @endif
                    <a href="{{ route('class.create') }}">
                        <button class="btn btn-primary">Add New</button><br/><br/>
                    </a>
                    <table class="table">
                        <thead>
                            <th>#</th>
                            <th>Name</th>
                            <th>Teacher</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            @foreach($classes as $key => $class)
                                <tr>
                                    <td>{{ $key+$classes->firstItem() }}</td>
                                    <td>{{ $class->name }}</td>
                                    <td>{{ $class->teacher->name }}</td>
                                    <td>
                                        <a href="{{ route('class.show', $class->id) }}">
                                            <button type="button" class="btn btn-warning" >Show</button>
                                        </a>
                                        <a href="{{ route('class.edit', $class->id) }}">
                                            <button type="button" class="btn btn-info" >Edit</button>
                                        </a>
                                        <button type="button" class="btn btn-danger"
                                            onclick="$('#delete-form-{{ $class->id }}').submit();">
                                            Delete
                                        </button>
                                        <form id="delete-form-{{ $class->id }}"
                                            action="{{ route('class.destroy', $class->id) }}"
                                            method="post" style="display: none;">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                        </form>
                                        <button type="button" class="btn btn-primary"
                                            onclick="event.preventDefault();
                                                        $('#download-form-{{ $class->id }}').submit();">
                                            Download</button>
                                        <form id="download-form-{{ $class->id }}"
                                            action="{{ route('class.getPDF') }}"
                                            method="POST" style="display: none;">
                                            <input type="hidden" name="id" value="{{ $class->id }}">
                                            {{ csrf_field() }}
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <p>Page {{ $classes->currentPage() }} of {{ $classes->lastPage() }}</p>
                    <a href="{{ $classes->previousPageUrl() }}">
                        <button type="button" class="btn btn-default"
                            @if($classes->currentPage() == 1)
                                disabled
                            @endif >
                            <<
                        </button>
                    </a>
                    <a href="{{ $classes->nextPageUrl() }}">
                        <button type="button" class="btn btn-default"
                            @if($classes->currentPage() == $classes->lastPage())
                                disabled
                            @endif>
                            >>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/class/pdf_template.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Download PDF</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <style type="text/css">
        body {
            background-color: #fff;
        }
    </style>
</head>
<body>
    <div class="container">
        @foreach($classes as $class)
            <div class="row">
                <div class="col-md-12">
                    <p>
                        Classroom: {{ $class->name }}<br>
                        Teacher: {{ $class->teacher->name }}
                    </p>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col-md-12">
                    <span>Student list</span>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($class->students as $key => $student)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $student->name }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        @endforeach
    </div>
</body>
</html>

resources/views/class/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ Breadcrumbs::render('class.show', $class->id) }}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Class</div>

                <div class="card-body">
                    @if (session('flash_data'))
                        <div class="alert alert-success">
                            {{ session('flash_data') }}
                        </div>
                    @endif
                    <p>
                        Teacher: {{ $class->teacher->name }}
                        <a href="{{ route('class.edit', $class->id) }}">
                            <button type="button" class="btn btn-info">Change</button>
                        </a>
                    </p>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                        Add New Student
                    </button><br/><br/>
                    <table class="table">
                        <thead>
                            <th>#</th>
                            <th>Name</th>
                        </thead>
                        <tbody>
                            @foreach($class->students as $key => $student)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $student->name }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="modal fade" id="exampleModal" tabindex="-1"
            role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($students as $key => $student)
                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $student->name }}</td>
                                        <td>
                                            <button type="button" class="btn btn-primary"
                                                onclick="$('#add-form-{{ $student->id }}').submit();">
                                                Add
                                            </button>
                                            <form id="add-form-{{ $student->id }}"
                                                action="{{ route('student.update', $student->id) }}"
                                                method="post" style="display: none;">
                                                {{ csrf_field() }}
                                                {{ method_field('PUT') }}
                                                <input type="hidden" name="url" value="class.show">
                                                <input type="hidden" name="class_id" value="{{ $class->id }}">
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection