routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function() {
    Route::resource('teacher', 'TeacherController', ['except' => ['show']]);
    Route::resource('student', 'StudentController', ['except' => ['show']]);
    Route::resource('class', 'ClassController');
    Route::get('/class/pdf/download', 'ClassController@download')->name('class.download');
    Route::post('/class/pdf/download', 'ClassController@getPDF')->name('class.getPDF');
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    public function classes() {
        return $this->belongsTo('App\Classes', 'class_id');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB, Exception, Validator;
use App\Classes;
use App\Student;

class StudentController extends Controller
{
    public function index(Request $request)
    {
        $students = Student::paginate(10);
        $data = [
            'students' => $students
        ];
        return view('student.index', $data);
    }

    public function create()
    {
        $classes = Classes::all();
        $data = [
            'classes' => $classes
        ];
        return view('student.create', $data);
    }

    public function store(Request $request)
    {
        DB::beginTransaction();
        try {
            $validator = Validator::make($request->all(), [
                'name' => 'required|min:3|max:50',
                'class_id' => 'required'
            ]);
            if($validator->fails()) {
                return redirect('student/create')->withErrors($validator)->withInput();
            }

            $student = new Student();
            $student->name = $request->name;
            $student->class_id = $request->class_id;
            $student->save();
            DB::commit();

            return redirect()->route('student.index')->with('flash_data', 'Data successfully created!');
        } catch(Exception $e) {
            DB::rollback();
            return view('errors.500');
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $student = Student::find($id);
        if(empty($student)) {
            return view('errors.404');
        }
        $classes = Classes::all();
        $data = [
            'student' => $student,
            'classes' => $classes
        ];
        return view('student.edit', $data);
    }

    public function update(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            if($request->url) {
                $validator = Validator::make($request->all(), [
                    'class_id' => 'required'
                ]);
            } else {
                $validator = Validator::make($request->all(), [
                    'name' => 'required|min:3|max:50',
                    'class_id' => 'required'
                ]);
            }
            if($validator->fails()) {
                return redirect()->route('student.edit', $id)->withErrors($validator)->withInput();
            }

            $student = Student::find($id);
            if(empty($student)) {
                return view('errors.500');
            }
            if(!$request->url) {
                $student->name = $request->name;
            }
            $student->class_id = $request->class_id;
            $student->save();
            DB::commit();

            if(!$request->url) {
                return redirect()->route('student.index')->with('flash_data', 'Data successfully updated!');
            } else {
                return redirect()->route('class.show', $request->class_id)
                                 ->with('flash_data', 'Data successfully updated!');
            }
        } catch(Exception $e) {
            DB::rollback();
            return view('errors.500');
        }
    }

    public function destroy(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $student = Student::find($id);
            if(empty($student)) {
                return view('errors.500');
            }
            $student->delete();
            DB::commit();

            return redirect()->route('student.index')->with('flash_data', 'Data successfully deleted!');
        } catch(Exception $e) {
            DB::rollback();
            return view('errors.500');
        }
    }
}

resources/views/student/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ Breadcrumbs::render('student.create') }}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Student</div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            {{ $errors->all()[0] }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('student.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="class_id">Class</label>
                            <select name="class_id" class="form-control">
                                @foreach($classes as $class)
                                    <option value="{{ $class->id }}">{{ $class->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{{ route('student.index') }}">
                            <button type="button" class="btn btn-default">Cancel</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/student/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ Breadcrumbs::render('student.edit', $student) }}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Student</div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            {{ $errors->all()[0] }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('student.update', $student->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control" value="{{ $student->name }}">
                        </div>
                        <div class="form-group">
                            <label for="class_id">Student</label>
                            <select name="class_id" class="form-control">
                                @foreach($classes as $class)
                                    <option value="{{ $class->id }}"
                                        @if($class->id == $student->class_id)
                                            selected
                                        @endif >
                                        {{ $class->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{{ route('student.index') }}">
                            <button type="button" class="btn btn-default">Cancel</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/student/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ Breadcrumbs::render('student.index') }}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Student</div>

                <div class="card-body">
                    @if (session('flash_data'))
                        <div class="alert alert-success">
                            {{ session('flash_data') }}
                        </div>
                    @endif
                    <a href="{{ route('student.create') }}">
                        <button class="btn btn-primary">Add New</button><br/><br/>
                    </a>
                    <table class="table">
                        <thead>
                            <th>#</th>
                            <th>Name</th>
                            <th>Class</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            @foreach($students as $key => $student)
                                <tr>
                                    <td>{{ $key+$students->firstItem() }}</td>
                                    <td>{{ $student->name }}</td>
                                    <td>{{ $student->classes->name }}</td>
                                    <td>
                                        <a href="{{ route('student.edit', $student->id) }}">
                                            <button type="button" class="btn btn-info" >Edit</button>
                                        </a>
                                        <button type="button" class="btn btn-danger"
                                            onclick="$('#delete-form-{{ $student->id }}').submit();">
                                            Delete
                                        </button>
                                        <form id="delete-form-{{ $student->id }}"
                                            action="{{ route('student.destroy', $student->id) }}"
                                            method="post" style="display: none;">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <p>Page {{ $students->currentPage() }} of {{ $students->lastPage() }}</p>
                    <a href="{{ $students->previousPageUrl() }}">
                        <button type="button" class="btn btn-default"
                            @if($students->currentPage() == 1)
                                disabled
                            @endif >
                            <<
                        </button>
                    </a>
                    <a href="{{ $students->nextPageUrl() }}">
                        <button type="button" class="btn btn-default"
                            @if($students->currentPage() == $students->lastPage())
                                disabled
                            @endif >
                            >>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection