routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function() {
    Route::resource('teacher', 'TeacherController', ['except' => ['show']]);
    Route::resource('student', 'StudentController', ['except' => ['show']]);
    Route::resource('class', 'ClassController');
    Route::get('/class/pdf/download', 'ClassController@download')->name('class.download');
    Route::post('/class/pdf/download', 'ClassController@getPDF')->name('class.getPDF');
});

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    public function classes() {
        return $this->hasMany('App\Classes');
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB, Exception, Validator;
use App\Teacher;

class TeacherController extends Controller
{
    public function index(Request $request)
    {
        $teachers = Teacher::paginate(10);
        $data = [
            'teachers' => $teachers
        ];
        return view('teacher.index', $data);
    }

    public function create()
    {
        return view('teacher.create');
    }

    public function store(Request $request)
    {
        DB::beginTransaction();
        try {
            $validator = Validator::make($request->all(), [
                'name' => 'required|min:3|max:50'
            ]);
            if($validator->fails()) {
                return redirect('teacher/create')->withErrors($validator)->withInput();
            }

            $teacher = new Teacher();
            $teacher->name = $request->name;
            $teacher->save();
            DB::commit();

            return redirect()->route('teacher.index')->with('flash_data', 'Data successfully created!');
        } catch(Exception $e) {
            DB::rollback();
            return view('errors.500');
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $teacher = Teacher::find($id);
        if(empty($teacher)) {
            return view('errors.404');
        }
        $data = [
            'teacher' => $teacher
        ];
        return view('teacher.edit', $data);
    }

    public function update(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $validator = Validator::make($request->all(), [
                'name' => 'required|min:3|max:50'
            ]);
            if($validator->fails()) {
                return redirect()->route('teacher.edit', $id)->withErrors($validator)->withInput();
            }

            $teacher = Teacher::find($id);
            if(empty($teacher)) {
                return view('errors.500');
            }
            $teacher->name = $request->name;
            $teacher->save();
            DB::commit();

            return redirect()->route('teacher.index')->with('flash_data', 'Data successfully updated!');
        } catch(Exception $e) {
            DB::rollback();
            return view('errors.500');
        }
    }

    public function destroy(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $teacher = Teacher::find($id);
            if(empty($teacher)) {
                return view('errors.500');
            }
            $teacher->delete();
            DB::commit();

            return redirect()->route('teacher.index')->with('flash_data', 'Data successfully deleted!');
        } catch(Exception $e) {
            DB::rollback();
            return view('errors.500');
        }
    }
}

resources/views/teacher/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ Breadcrumbs::render('teacher.create') }}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Teacher</div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            {{ $errors->all()[0] }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('teacher.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{{ route('teacher.index') }}">
                            <button type="button" class="btn btn-default">Cancel</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/teacher/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ Breadcrumbs::render('teacher.edit', $teacher) }}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Teacher</div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            {{ $errors->all()[0] }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('teacher.update', $teacher->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control" value="{{ $teacher->name }}">
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{{ route('teacher.index') }}">
                            <button type="button" class="btn btn-default">Cancel</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/teacher/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ Breadcrumbs::render('teacher.index') }}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Teacher</div>

                <div class="card-body">
                    @if (session('flash_data'))
                        <div class="alert alert-success">
                            {{ session('flash_data') }}
                        </div>
                    @endif
                    <a href="{{ route('teacher.create') }}">
                        <button class="btn btn-primary">Add New</button><br/><br/>
                    </a>
                    <table class="table">
                        <thead>
                            <th>#</th>
                            <th>Name</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            @foreach($teachers as $key => $teacher)
                                <tr>
                                    <td>{{ $key+$teachers->firstItem() }}</td>
                                    <td>{{ $teacher->name }}</td>
                                    <td>
                                        <a href="{{ route('teacher.edit', $teacher->id) }}">
                                            <button type="button" class="btn btn-info" >Edit</button>
                                        </a>
                                        <button type="button" class="btn btn-danger"
                                            onclick="$('#delete-form-{{ $teacher->id }}').submit();">
                                            Delete
                                        </button>
                                        <form id="delete-form-{{ $teacher->id }}"
                                            action="{{ route('teacher.destroy', $teacher->id) }}"
                                            method="post" style="display: none;">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <p>Page {{ $teachers->currentPage() }} of {{ $teachers->lastPage() }}</p>
                    <a href="{{ $teachers->previousPageUrl() }}">
                        <button type="button" class="btn btn-default"
                            @if($teachers->currentPage() == 1)
                                disabled
                            @endif>
                            <<
                        </button>
                    </a>
                    <a href="{{ $teachers->nextPageUrl() }}">
                        <button type="button" class="btn btn-default"
                            @if($teachers->currentPage() == $teachers->lastPage())
                                disabled
                            @endif>
                            >>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection